/** Re-export para retrocompatibilidade de imports diretos. */
export {
  CODIGOS_PAR,
  CODIGOS_CORE,
  CODIGOS_RECEBER,
  CODIGOS_DESEMPATE,
  CODIGOS_EXPRESSAR,
  PARES_FORCADOS,
  PARES_RECEBER,
  PARES_EXPRESSAR,
  PARES_DESEMPATE_TODOS,
  paresDesempatePara,
  LABEL_LINGUAGEM,
  parPorId,
  tituloBloco,
  TOTAL_CORE,
  TOTAL_DESEMPATE_MAX,
  TOTAL_EXPRESSAR,
  type CodigoPar,
  type CodigoCore,
  type CodigoReceber,
  type CodigoDesempate,
  type CodigoExpressar,
} from "./perguntas/index.js";
